# Site settings
title: Majorkamo's Site of Major Awesomeness
email: noone@nowhere.net
description: > # this means to ignore newlines until "baseurl:"
  Find all the stuff that Majorkamo is working on right here!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://majorkamo.com" # the base hostname & protocol for your site
twitter_username: majorkamo
github_username:  majorkamo02

# Build settings
markdown: kramdown
